# Generated by Django 3.0.4 on 2020-04-02 23:10

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200402_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_name',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('trash', 'Trash'), ('paper', 'Paper'), ('plastic', 'Plastic'), ('metal', 'Metal'), ('cardboard', 'Cardboard')], default='Trash', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=data.models.get_upload_to),
        ),
    ]
