# Generated by Django 3.0.4 on 2020-04-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200402_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('trash', 'Trash'), ('paper', 'Paper'), ('plastic', 'Plastic'), ('metal', 'Metal'), ('cardboard', 'Cardboard'), ('glass', 'Glass')], default='Trash', max_length=10),
        ),
    ]
